<ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
	<li>
        <div class="input-box">
			<label for="cryptocurrency-BTC">Bitcoin</label>
            <input type="radio" value="BTC" name="payment[cryptocurrency]" id="cryptocurrency-BTC" class="radio">
        </div>
        <div class="input-box">
            <label for="cryptocurrency-LTC">Litcoin</label>
			<input type="radio" value="LTC" name="payment[cryptocurrency]" id="cryptocurrency-LTC" class="radio">
        </div>		
    </li>
</ul>
